In [88]:
import pandas as pd
import numpy as np

In [4]:
car = pd.read_csv("car data.csv")

In [3]:
car

Unnamed: 0                    name   company  year   Price  kms_driven  \
0             0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1             1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2             2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3             3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4             4               Ford Figo      Ford  2012  175000       41000   
..          ...                     ...       ...   ...     ...         ...   
811         811      Maruti Suzuki Ritz    Maruti  2011  270000       50000   
812         812          Tata Indica V2      Tata  2009  110000       30000   
813         813    Toyota Corolla Altis    Toyota  2009  300000      132000   
814         814            Tata Zest XM      Tata  2018  260000       27000   
815         815      Mahindra Quanto C8  Mahindra  2013  390000       40000   

    fuel_type  
0      Petrol  
1      Diesel  
2      Petrol  
3      Diesel  
4      Diesel  
..        ...  
811    Petrol  
812    Diesel  
813    Petrol  
814    Diesel  
815    Diesel  

[816 rows x 7 columns]

In [5]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  816 non-null    int64 
 1   name        816 non-null    object
 2   company     816 non-null    object
 3   year        816 non-null    int64 
 4   Price       816 non-null    int64 
 5   kms_driven  816 non-null    int64 
 6   fuel_type   816 non-null    object
dtypes: int64(4), object(3)
memory usage: 44.8+ KB


In [5]:
df.describe()

Unnamed: 0         year         Price     kms_driven
count  816.000000   816.000000  8.160000e+02     816.000000
mean   407.500000  2012.444853  4.117176e+05   46275.531863
std    235.703203     4.002992  4.751844e+05   34297.428044
min      0.000000  1995.000000  3.000000e+04       0.000000
25%    203.750000  2010.000000  1.750000e+05   27000.000000
50%    407.500000  2013.000000  2.999990e+05   41000.000000
75%    611.250000  2015.000000  4.912500e+05   56818.500000
max    815.000000  2019.000000  8.500003e+06  400000.000000

In [6]:
car['year'].unique()

array([2007, 2006, 2014, 2012, 2013, 2016, 2015, 2010, 2017, 2008, 2018,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001],
      dtype=int64)

In [7]:
car['company'].unique()

array(['Hyundai', 'Mahindra', 'Ford', 'Maruti', 'Skoda', 'Audi', 'Toyota',
       'Renault', 'Honda', 'Datsun', 'Mitsubishi', 'Tata', 'Volkswagen',
       'Chevrolet', 'Mini', 'BMW', 'Nissan', 'Hindustan', 'Fiat', 'Force',
       'Mercedes', 'Land', 'Jaguar', 'Jeep', 'Volvo'], dtype=object)

In [8]:
car['name'].unique()

array(['Hyundai Santro Xing', 'Mahindra Jeep CL550', 'Hyundai Grand i10',
       'Ford EcoSport Titanium', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente', 'Maruti Suzuki Alto',
       'Skoda Fabia Classic', 'Maruti Suzuki Stingray',
       'Hyundai Elite i20', 'Mahindra Scorpio SLE', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Hyundai i20 Sportz',
       'Maruti Suzuki Vitara', 'Mahindra Bolero DI',
       'Maruti Suzuki Swift', 'Maruti Suzuki Wagon', 'Toyota Innova 2.0',
       'Renault Lodgy 85', 'Skoda Yeti Ambition', 'Maruti Suzuki Baleno',
       'Renault Duster 110', 'Renault Duster 85', 'Honda City 1.5',
       'Maruti Suzuki Dzire', 'Honda Amaze', 'Honda Amaze 1.5',
       'Honda City', 'Datsun Redi GO', 'Maruti Suzuki SX4',
       'Mitsubishi Pajero Sport', 'Honda City ZX', 'Tata Indigo eCS',
       'Volkswagen Polo Highline', 'Chevrolet Spark LS',
       'Renault Duster 110PS', 'Mini Cooper S', 'Skoda Fabia 1.2L',
       'Renault Duster', 'Mahindra Scor

In [11]:
car['Price'].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  285000,  340000,   70000,  289999,  849999,
        749999,  274999,  984999,  599999,  244999,  474999,  245000,
        169500,  275

In [12]:
car['kms_driven'].unique()

array([ 45000,     40,  28000,  36000,  41000,  25000,  24530,  60000,
        30000,  32000,  48660,   4000,  16934,  43000,  35550,  39522,
        39000,  55000,  72000,  15975,  70000,  23452,  35522,  48508,
        15487,  82000,  20000,  68000,  38000,  27000,  33000,  46000,
        16000,  47000,  35000,  30874,  15000,  29685, 130000,  19000,
        54000,  13000,  38200,  22000,  50000,  13500,   3600,  45863,
        60500,  12500,  18000,  13349,  29000,  44000,  42000,  14000,
        49000,  36200,  51000, 104000,  33333,  33600,   5600,   7500,
        24330,  65480, 200000,  59000,  99000,   2800,  21000,  11000,
        66000,   3000,   7000,  38500,  37200,  43200,  24800,  45872,
        40000,  11400,  97200,  52000,  31000, 175430,  37000,  65000,
         3350,  75000,  62000,  73000,   2200,  54870,  34580,  97000,
           60,  80200,   3200,      0,   5000,    588,  71200, 175400,
         9300,  56758,  10000,  56450,  56000,  32700,   9000,     73,
      

In [13]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [14]:
car

Unnamed: 0                    name   company  year   Price  kms_driven  \
0             0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1             1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2             2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3             3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4             4               Ford Figo      Ford  2012  175000       41000   
..          ...                     ...       ...   ...     ...         ...   
811         811      Maruti Suzuki Ritz    Maruti  2011  270000       50000   
812         812          Tata Indica V2      Tata  2009  110000       30000   
813         813    Toyota Corolla Altis    Toyota  2009  300000      132000   
814         814            Tata Zest XM      Tata  2018  260000       27000   
815         815      Mahindra Quanto C8  Mahindra  2013  390000       40000   

    fuel_type  
0      Petrol  
1      Diesel  
2      Petrol  
3      Diesel  
4      Diesel  
..        ...  
811    Petrol  
812    Diesel  
813    Petrol  
814    Diesel  
815    Diesel  

[816 rows x 7 columns]

## Checking Proper Data

In [16]:
car['name'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: name
Non-Null Count  Dtype 
--------------  ----- 
816 non-null    object
dtypes: object(1)
memory usage: 6.5+ KB


In [17]:
car['company'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: company
Non-Null Count  Dtype 
--------------  ----- 
816 non-null    object
dtypes: object(1)
memory usage: 6.5+ KB


In [18]:
car['year'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: year
Non-Null Count  Dtype
--------------  -----
816 non-null    int64
dtypes: int64(1)
memory usage: 6.5 KB


In [19]:
car['Price'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: Price
Non-Null Count  Dtype
--------------  -----
816 non-null    int64
dtypes: int64(1)
memory usage: 6.5 KB


In [20]:
car['kms_driven'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: kms_driven
Non-Null Count  Dtype
--------------  -----
816 non-null    int64
dtypes: int64(1)
memory usage: 6.5 KB


In [21]:
car['fuel_type'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 816 entries, 0 to 815
Series name: fuel_type
Non-Null Count  Dtype 
--------------  ----- 
816 non-null    object
dtypes: object(1)
memory usage: 6.5+ KB


In [22]:
car['name'].describe()

count                     816
unique                    254
top       Maruti Suzuki Swift
freq                       51
Name: name, dtype: object

In [23]:
car.shape

(816, 7)

In [25]:
car['name']

0         Hyundai Santro Xing
1         Mahindra Jeep CL550
2           Hyundai Grand i10
3      Ford EcoSport Titanium
4                   Ford Figo
                ...          
811        Maruti Suzuki Ritz
812            Tata Indica V2
813      Toyota Corolla Altis
814              Tata Zest XM
815        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [26]:
car['company']

0       Hyundai
1      Mahindra
2       Hyundai
3          Ford
4          Ford
         ...   
811      Maruti
812        Tata
813      Toyota
814        Tata
815    Mahindra
Name: company, Length: 816, dtype: object

In [27]:
car['Price']

0       80000
1      425000
2      325000
3      575000
4      175000
        ...  
811    270000
812    110000
813    300000
814    260000
815    390000
Name: Price, Length: 816, dtype: int64

In [28]:
car['year']

0      2007
1      2006
2      2014
3      2014
4      2012
       ... 
811    2011
812    2009
813    2009
814    2018
815    2013
Name: year, Length: 816, dtype: int64

In [29]:
car['kms_driven']

0       45000
1          40
2       28000
3       36000
4       41000
        ...  
811     50000
812     30000
813    132000
814     27000
815     40000
Name: kms_driven, Length: 816, dtype: int64

In [30]:
car['fuel_type']

0      Petrol
1      Diesel
2      Petrol
3      Diesel
4      Diesel
        ...  
811    Petrol
812    Diesel
813    Petrol
814    Diesel
815    Diesel
Name: fuel_type, Length: 816, dtype: object

In [31]:
car.describe()

Unnamed: 0         year         Price     kms_driven
count  816.000000   816.000000  8.160000e+02     816.000000
mean   407.500000  2012.444853  4.117176e+05   46275.531863
std    235.703203     4.002992  4.751844e+05   34297.428044
min      0.000000  1995.000000  3.000000e+04       0.000000
25%    203.750000  2010.000000  1.750000e+05   27000.000000
50%    407.500000  2013.000000  2.999990e+05   41000.000000
75%    611.250000  2015.000000  4.912500e+05   56818.500000
max    815.000000  2019.000000  8.500003e+06  400000.000000

## Cars Greater Than 60 Lakh

In [39]:
car[car['Price']<6e6]

Unnamed: 0                    name   company  year   Price  kms_driven  \
0             0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1             1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2             2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3             3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4             4               Ford Figo      Ford  2012  175000       41000   
..          ...                     ...       ...   ...     ...         ...   
810         811      Maruti Suzuki Ritz    Maruti  2011  270000       50000   
811         812          Tata Indica V2      Tata  2009  110000       30000   
812         813    Toyota Corolla Altis    Toyota  2009  300000      132000   
813         814            Tata Zest XM      Tata  2018  260000       27000   
814         815      Mahindra Quanto C8  Mahindra  2013  390000       40000   

    fuel_type  
0      Petrol  
1      Diesel  
2      Petrol  
3      Diesel  
4      Diesel  
..        ...  
810    Petrol  
811    Diesel  
812    Petrol  
813    Diesel  
814    Diesel  

[815 rows x 7 columns]

## Model

In [40]:
# dropping price because it's not a feature
x = car.drop(columns='Price')
y = car['Price']

In [41]:
x

Unnamed: 0                    name   company  year  kms_driven fuel_type
0             0     Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1             1     Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2             2       Hyundai Grand i10   Hyundai  2014       28000    Petrol
3             3  Ford EcoSport Titanium      Ford  2014       36000    Diesel
4             4               Ford Figo      Ford  2012       41000    Diesel
..          ...                     ...       ...   ...         ...       ...
810         811      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811         812          Tata Indica V2      Tata  2009       30000    Diesel
812         813    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813         814            Tata Zest XM      Tata  2018       27000    Diesel
814         815      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 6 columns]

In [42]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...  
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int64

In [70]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size=0.2)

In [71]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [72]:
ohe = OneHotEncoder()
ohe.fit(x[['name', 'company','fuel_type']])

OneHotEncoder()

In [73]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),
                                        remainder='passthrough')

In [74]:
lr = LinearRegression()

In [75]:
pipe = make_pipeline(column_trans,lr)

In [76]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [77]:
y_pred = pipe.predict(x_test)

In [78]:
y_pred

array([ 442321.1204134 ,  634379.27158595,  409898.40137657,
         85969.11987306,  573499.47090563,  681410.57742976,
        458859.94124135,  449935.02281059,  145654.94867773,
        280096.27688807,  252156.56608217,  200738.99572466,
        347070.14874771,  352263.64531571,  523141.56598856,
        641887.56380425,  593364.27669647,  392556.31043682,
        146215.22641772,  302646.07397567,  388161.31645088,
        350640.45232658,  399345.30812275,  107833.59518565,
         -7910.53918304,  333819.58322052,  -77092.57953431,
        412258.39036648,  420695.98563205,  341903.64682778,
        298540.37511737,  323202.35477074,  319388.87618233,
        180485.98145115,  602995.08264313,  122593.49093819,
       1299091.37692198,  402844.01833297,  309224.73760118,
        248365.36495463,  375503.96265711,  342263.53465144,
        244101.24792005,  257407.57796888,  406759.76994926,
        422774.17158495,  123704.75459538,  187856.30548723,
        472831.23356965,

In [79]:
r2_score(y_test,y_pred)

0.47910285979338374

In [87]:
scores = []
for i in range(1000):
    x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred = pipe.predict(x_test)
    print(r2_score(y_test,y_pred),i)
    scores.append(r2_score(y_test,y_pred))

0.6661069038751815 0
0.5048147429003093 1
0.6289449351607963 2
0.5556453423067457 3
0.8048033304001345 4
0.6629841880665786 5
0.6402903078808225 6
0.633290220253633 7
0.6842085346809162 8
0.5969262408589701 9
0.64623593832131 10
0.612071339521751 11
0.47588230839095247 12
0.6674934171683764 13
0.5726751364143832 14
0.6937720432057455 15
0.5004376339306607 16
0.6728040436436586 17
0.6189082659360687 18
0.6414695521842083 19
0.6511108764381215 20
0.6315827262871003 21
0.7110724747181748 22
0.651644682036574 23
0.5588678349522056 24
0.5019229054321841 25
0.6760818178707666 26
0.6972069121039444 27
0.734095079784996 28
0.6173233452061315 29
0.6161753411162991 30
0.6707447575207501 31
0.7578370758624349 32
0.7892895059416031 33
0.5769382612517833 34
0.6677681058307268 35
0.5907954228474013 36
0.6216484582533085 37
0.5593891737179069 38
0.7232143551089669 39
0.37139069039380745 40
0.6844222032729104 41
0.5788543214321622 42
0.6639119881414155 43
0.6685949529103836 44
0.6954475680261978 45
0.

In [90]:
np.argmax(scores)

433

In [91]:
scores[np.argmax(scores)]

0.8455753664645759

In [94]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred = pipe.predict(x_test)
r2_score(y_test,y_pred)

0.8455753664645759

In [96]:
import pickle

In [97]:
pickle.dump(pipe,open('LinearRegressionModel.pk1','wb'))

In [102]:
car

Unnamed: 0                    name   company  year   Price  kms_driven  \
0             0     Hyundai Santro Xing   Hyundai  2007   80000       45000   
1             1     Mahindra Jeep CL550  Mahindra  2006  425000          40   
2             2       Hyundai Grand i10   Hyundai  2014  325000       28000   
3             3  Ford EcoSport Titanium      Ford  2014  575000       36000   
4             4               Ford Figo      Ford  2012  175000       41000   
..          ...                     ...       ...   ...     ...         ...   
810         811      Maruti Suzuki Ritz    Maruti  2011  270000       50000   
811         812          Tata Indica V2      Tata  2009  110000       30000   
812         813    Toyota Corolla Altis    Toyota  2009  300000      132000   
813         814            Tata Zest XM      Tata  2018  260000       27000   
814         815      Mahindra Quanto C8  Mahindra  2013  390000       40000   

    fuel_type  
0      Petrol  
1      Diesel  
2      Petrol  
3      Diesel  
4      Diesel  
..        ...  
810    Petrol  
811    Diesel  
812    Petrol  
813    Diesel  
814    Diesel  

[815 rows x 7 columns]

In [106]:
pipe.predict(pd.DataFrame([['2','Hyundai Grand i10','Hyundai','2014','28000','Petrol']]),
             columns=['Unnamed: 0','name','company','year','kms_driven','fuel_type'])

ValueError: columns are missing: {'kms_driven', 'Unnamed: 0', 'year'}